spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 10.15.0.4:9300
      cluster-name: elasticsearch
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elasticsearch?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    port: 6379
    host: 10.15.0.4

server:
  port: 8989
  servlet:
    jsp:
      init-parameters:
        development: true




mybatis:
  mapper-locations: com/baizhi/mapper/*.xml
logging:
  level:
    root: info
    com.baizhi.dao: debug
